import AppKit
import Foundation

// Comprehensive SF Symbols list organized by category
// Based on SF Symbols 5.0
enum SFSymbols {
    static let allSymbols: [SFSymbol] = {
        var symbols: [SFSymbol] = []

        // General
        symbols.append(contentsOf: general.map { SFSymbol(id: $0, category: .general) })

        // Communication
        symbols.append(contentsOf: communication.map { SFSymbol(id: $0, category: .communication) })

        // Weather
        symbols.append(contentsOf: weather.map { SFSymbol(id: $0, category: .weather) })

        // Objects & Tools
        symbols.append(contentsOf: objectsAndTools.map { SFSymbol(id: $0, category: .objectsAndTools) })

        // Devices
        symbols.append(contentsOf: devices.map { SFSymbol(id: $0, category: .devices) })

        // Connectivity
        symbols.append(contentsOf: connectivity.map { SFSymbol(id: $0, category: .connectivity) })

        // Transportation
        symbols.append(contentsOf: transportation.map { SFSymbol(id: $0, category: .transportation) })

        // Human
        symbols.append(contentsOf: human.map { SFSymbol(id: $0, category: .human) })

        // Nature
        symbols.append(contentsOf: nature.map { SFSymbol(id: $0, category: .nature) })

        // Editing
        symbols.append(contentsOf: editing.map { SFSymbol(id: $0, category: .editing) })

        // Text Formatting
        symbols.append(contentsOf: textFormatting.map { SFSymbol(id: $0, category: .textFormatting) })

        // Media
        symbols.append(contentsOf: media.map { SFSymbol(id: $0, category: .media) })

        // Keyboard
        symbols.append(contentsOf: keyboard.map { SFSymbol(id: $0, category: .keyboard) })

        // Commerce
        symbols.append(contentsOf: commerce.map { SFSymbol(id: $0, category: .commerce) })

        // Time
        symbols.append(contentsOf: time.map { SFSymbol(id: $0, category: .time) })

        // Health
        symbols.append(contentsOf: health.map { SFSymbol(id: $0, category: .health) })

        // Shapes
        symbols.append(contentsOf: shapes.map { SFSymbol(id: $0, category: .shapes) })

        // Arrows
        symbols.append(contentsOf: arrows.map { SFSymbol(id: $0, category: .arrows) })

        // Indices
        symbols.append(contentsOf: indices.map { SFSymbol(id: $0, category: .indices) })

        // Math
        symbols.append(contentsOf: math.map { SFSymbol(id: $0, category: .math) })

        // Gaming
        symbols.append(contentsOf: gaming.map { SFSymbol(id: $0, category: .gaming) })

        // Privacy
        symbols.append(contentsOf: privacy.map { SFSymbol(id: $0, category: .privacy) })

        // Home
        symbols.append(contentsOf: home.map { SFSymbol(id: $0, category: .home) })

        // Fitness
        symbols.append(contentsOf: fitness.map { SFSymbol(id: $0, category: .fitness) })

        // Filter out symbols not available on the current macOS version
        return symbols.filter {
            NSImage(systemSymbolName: $0.name, accessibilityDescription: nil) != nil
        }
    }()

    // MARK: - General

    static let general: [String] = [
        "star", "star.fill", "star.leadinghalf.filled", "star.circle", "star.circle.fill",
        "star.square", "star.square.fill", "star.slash", "star.slash.fill",
        "heart", "heart.fill", "heart.circle", "heart.circle.fill", "heart.slash", "heart.slash.fill",
        "heart.slash.circle", "heart.slash.circle.fill",
        "bolt", "bolt.fill", "bolt.circle", "bolt.circle.fill", "bolt.slash", "bolt.slash.fill",
        "bolt.slash.circle", "bolt.slash.circle.fill", "bolt.trianglebadge.exclamationmark",
        "bolt.trianglebadge.exclamationmark.fill", "bolt.shield", "bolt.shield.fill",
        "eye", "eye.fill", "eye.circle", "eye.circle.fill", "eye.slash", "eye.slash.fill",
        "eye.slash.circle", "eye.slash.circle.fill",
        "tshirt", "tshirt.fill",
        "tag", "tag.fill", "tag.circle", "tag.circle.fill", "tag.slash", "tag.slash.fill",
        "bell", "bell.fill", "bell.circle", "bell.circle.fill", "bell.badge", "bell.badge.fill",
        "bell.slash", "bell.slash.fill", "bell.slash.circle", "bell.slash.circle.fill",
        "bell.and.waveform", "bell.and.waveform.fill",
        "flag", "flag.fill", "flag.circle", "flag.circle.fill", "flag.slash", "flag.slash.fill",
        "flag.slash.circle", "flag.slash.circle.fill",
        "flag.2.crossed", "flag.2.crossed.fill", "flag.2.crossed.circle", "flag.2.crossed.circle.fill",
        "flag.filled.and.flag.crossed", "flag.and.flag.filled.crossed",
        "location", "location.fill", "location.circle", "location.circle.fill",
        "location.slash", "location.slash.fill", "location.slash.circle", "location.slash.circle.fill",
        "location.north", "location.north.fill", "location.north.circle", "location.north.circle.fill",
        "location.north.line", "location.north.line.fill",
        "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
        "bookmark", "bookmark.fill", "bookmark.circle", "bookmark.circle.fill",
        "bookmark.slash", "bookmark.slash.fill",
        "rosette", "graduationcap", "graduationcap.fill", "graduationcap.circle", "graduationcap.circle.fill",
        "checkmark.seal", "checkmark.seal.fill", "xmark.seal", "xmark.seal.fill",
        "exclamationmark.triangle", "exclamationmark.triangle.fill",
        "drop", "drop.fill", "drop.circle", "drop.circle.fill",
        "drop.triangle", "drop.triangle.fill",
        "flame", "flame.fill", "flame.circle", "flame.circle.fill",
        "bolt.horizontal", "bolt.horizontal.fill", "bolt.horizontal.circle", "bolt.horizontal.circle.fill",
        "flashlight.off.fill", "flashlight.on.fill",
        "camera", "camera.fill", "camera.circle", "camera.circle.fill",
        "camera.shutter.button", "camera.shutter.button.fill",
        "camera.on.rectangle", "camera.on.rectangle.fill",
        "gear", "gearshape", "gearshape.fill", "gearshape.circle", "gearshape.circle.fill",
        "gearshape.2", "gearshape.2.fill",
        "signature", "line.3.crossed.swirl.circle", "line.3.crossed.swirl.circle.fill"
    ]

    // MARK: - Communication

    static let communication: [String] = [
        "mic", "mic.fill", "mic.circle", "mic.circle.fill", "mic.slash", "mic.slash.fill",
        "mic.slash.circle", "mic.slash.circle.fill",
        "mic.badge.plus", "mic.fill.badge.plus",
        "message", "message.fill", "message.circle", "message.circle.fill",
        "message.badge", "message.badge.fill", "message.badge.filled.fill",
        "bubble.right", "bubble.right.fill", "bubble.right.circle", "bubble.right.circle.fill",
        "bubble.left", "bubble.left.fill", "bubble.left.circle", "bubble.left.circle.fill",
        "bubble.left.and.bubble.right", "bubble.left.and.bubble.right.fill",
        "bubble.middle.bottom", "bubble.middle.bottom.fill",
        "bubble.middle.top", "bubble.middle.top.fill",
        "exclamationmark.bubble", "exclamationmark.bubble.fill",
        "quote.bubble", "quote.bubble.fill",
        "star.bubble", "star.bubble.fill",
        "character.bubble", "character.bubble.fill",
        "text.bubble", "text.bubble.fill",
        "captions.bubble", "captions.bubble.fill",
        "plus.bubble", "plus.bubble.fill",
        "rectangle.3.group.bubble.left", "rectangle.3.group.bubble.left.fill",
        "ellipsis.bubble", "ellipsis.bubble.fill",
        "ellipsis.vertical.bubble", "ellipsis.vertical.bubble.fill",
        "phone", "phone.fill", "phone.circle", "phone.circle.fill",
        "phone.badge.plus", "phone.fill.badge.plus",
        "phone.connection", "phone.fill.connection",
        "phone.arrow.up.right", "phone.arrow.up.right.fill",
        "phone.arrow.down.left", "phone.arrow.down.left.fill",
        "phone.arrow.right", "phone.arrow.right.fill",
        "phone.down", "phone.down.fill", "phone.down.circle", "phone.down.circle.fill",
        "teletype", "teletype.circle", "teletype.circle.fill",
        "teletype.answer", "teletype.answer.circle", "teletype.answer.circle.fill",
        "video", "video.fill", "video.circle", "video.circle.fill",
        "video.slash", "video.slash.fill",
        "video.badge.plus", "video.fill.badge.plus",
        "video.badge.checkmark", "video.fill.badge.checkmark",
        "video.badge.ellipsis", "video.fill.badge.ellipsis",
        "arrow.up.right.video", "arrow.up.right.video.fill",
        "arrow.down.left.video", "arrow.down.left.video.fill",
        "questionmark.video", "questionmark.video.fill",
        "envelope", "envelope.fill", "envelope.circle", "envelope.circle.fill",
        "envelope.open", "envelope.open.fill",
        "envelope.badge", "envelope.badge.fill",
        "envelope.badge.shield.half.filled", "envelope.badge.shield.half.filled.fill",
        "mail", "mail.fill",
        "mail.stack", "mail.stack.fill",
        "mail.and.text.magnifyingglass",
        "paperclip", "paperclip.circle", "paperclip.circle.fill",
        "paperclip.badge.ellipsis",
        "rectangle.and.paperclip",
        "link", "link.circle", "link.circle.fill",
        "link.badge.plus",
        "person.crop.circle.badge.questionmark", "person.crop.circle.badge.questionmark.fill",
        "person.2.wave.2", "person.2.wave.2.fill",
        "shared.with.you", "shared.with.you.slash"
    ]

    // MARK: - Weather

    static let weather: [String] = [
        "sun.min", "sun.min.fill", "sun.max", "sun.max.fill",
        "sun.max.circle", "sun.max.circle.fill",
        "sun.and.horizon", "sun.and.horizon.fill",
        "sun.and.horizon.circle", "sun.and.horizon.circle.fill",
        "sun.dust", "sun.dust.fill", "sun.dust.circle", "sun.dust.circle.fill",
        "sun.haze", "sun.haze.fill", "sun.haze.circle", "sun.haze.circle.fill",
        "sunrise", "sunrise.fill", "sunrise.circle", "sunrise.circle.fill",
        "sunset", "sunset.fill", "sunset.circle", "sunset.circle.fill",
        "moon", "moon.fill", "moon.circle", "moon.circle.fill",
        "moon.stars", "moon.stars.fill", "moon.stars.circle", "moon.stars.circle.fill",
        "moon.zzz", "moon.zzz.fill",
        "sparkle", "sparkles", "sparkles.rectangle.stack", "sparkles.rectangle.stack.fill",
        "cloud", "cloud.fill", "cloud.circle", "cloud.circle.fill",
        "cloud.drizzle", "cloud.drizzle.fill", "cloud.drizzle.circle", "cloud.drizzle.circle.fill",
        "cloud.rain", "cloud.rain.fill", "cloud.rain.circle", "cloud.rain.circle.fill",
        "cloud.heavyrain", "cloud.heavyrain.fill", "cloud.heavyrain.circle", "cloud.heavyrain.circle.fill",
        "cloud.fog", "cloud.fog.fill", "cloud.fog.circle", "cloud.fog.circle.fill",
        "cloud.hail", "cloud.hail.fill", "cloud.hail.circle", "cloud.hail.circle.fill",
        "cloud.snow", "cloud.snow.fill", "cloud.snow.circle", "cloud.snow.circle.fill",
        "cloud.sleet", "cloud.sleet.fill", "cloud.sleet.circle", "cloud.sleet.circle.fill",
        "cloud.bolt", "cloud.bolt.fill", "cloud.bolt.circle", "cloud.bolt.circle.fill",
        "cloud.bolt.rain", "cloud.bolt.rain.fill", "cloud.bolt.rain.circle", "cloud.bolt.rain.circle.fill",
        "cloud.sun", "cloud.sun.fill", "cloud.sun.circle", "cloud.sun.circle.fill",
        "cloud.sun.rain", "cloud.sun.rain.fill", "cloud.sun.rain.circle", "cloud.sun.rain.circle.fill",
        "cloud.sun.bolt", "cloud.sun.bolt.fill", "cloud.sun.bolt.circle", "cloud.sun.bolt.circle.fill",
        "cloud.moon", "cloud.moon.fill", "cloud.moon.circle", "cloud.moon.circle.fill",
        "cloud.moon.rain", "cloud.moon.rain.fill", "cloud.moon.rain.circle", "cloud.moon.rain.circle.fill",
        "cloud.moon.bolt", "cloud.moon.bolt.fill", "cloud.moon.bolt.circle", "cloud.moon.bolt.circle.fill",
        "smoke", "smoke.fill", "smoke.circle", "smoke.circle.fill",
        "wind", "wind.circle", "wind.circle.fill", "wind.snow", "wind.snow.circle", "wind.snow.circle.fill",
        "tornado", "tornado.circle", "tornado.circle.fill",
        "tropicalstorm", "tropicalstorm.circle", "tropicalstorm.circle.fill",
        "hurricane", "hurricane.circle", "hurricane.circle.fill",
        "thermometer.sun", "thermometer.sun.fill", "thermometer.sun.circle", "thermometer.sun.circle.fill",
        "thermometer.snowflake", "thermometer.snowflake.circle", "thermometer.snowflake.circle.fill",
        "thermometer.medium", "thermometer.low", "thermometer.high",
        "thermometer.variable.and.figure", "thermometer.variable.and.figure.circle", "thermometer.variable.and.figure.circle.fill",
        "aqi.low", "aqi.medium", "aqi.high",
        "humidity", "humidity.fill",
        "snowflake", "snowflake.circle", "snowflake.circle.fill", "snowflake.slash",
        "rainbow", "umbrella", "umbrella.fill", "umbrella.percent", "umbrella.percent.fill"
    ]

    // MARK: - Objects & Tools

    static let objectsAndTools: [String] = [
        "pencil", "pencil.circle", "pencil.circle.fill",
        "pencil.slash",
        "pencil.line",
        "pencil.and.outline", "pencil.and.scribble",
        "highlighter",
        "pencil.and.ruler", "pencil.and.ruler.fill",
        "eraser", "eraser.fill", "eraser.line.dashed", "eraser.line.dashed.fill",
        "trash", "trash.fill", "trash.circle", "trash.circle.fill",
        "trash.slash", "trash.slash.fill",
        "folder", "folder.fill", "folder.circle", "folder.circle.fill",
        "folder.badge.plus", "folder.fill.badge.plus",
        "folder.badge.minus", "folder.fill.badge.minus",
        "folder.badge.questionmark",
        "folder.badge.gearshape",
        "plus.rectangle.on.folder", "plus.rectangle.on.folder.fill",
        "questionmark.folder", "questionmark.folder.fill",
        "paperplane", "paperplane.fill", "paperplane.circle", "paperplane.circle.fill",
        "tray", "tray.fill", "tray.circle", "tray.circle.fill",
        "tray.and.arrow.up", "tray.and.arrow.up.fill",
        "tray.and.arrow.down", "tray.and.arrow.down.fill",
        "tray.2", "tray.2.fill", "tray.full", "tray.full.fill",
        "archivebox", "archivebox.fill", "archivebox.circle", "archivebox.circle.fill",
        "xmark.bin", "xmark.bin.fill", "xmark.bin.circle", "xmark.bin.circle.fill",
        "doc", "doc.fill", "doc.circle", "doc.circle.fill",
        "doc.badge.plus", "doc.fill.badge.plus",
        "doc.badge.gearshape", "doc.badge.gearshape.fill",
        "doc.badge.ellipsis",
        "doc.text", "doc.text.fill",
        "doc.zipper",
        "doc.on.doc", "doc.on.doc.fill",
        "doc.on.clipboard", "doc.on.clipboard.fill",
        "clipboard", "clipboard.fill",
        "list.bullet.clipboard", "list.bullet.clipboard.fill",
        "list.clipboard", "list.clipboard.fill",
        "note", "note.text", "note.text.badge.plus",
        "calendar", "calendar.circle", "calendar.circle.fill",
        "calendar.badge.plus", "calendar.badge.minus",
        "calendar.badge.clock", "calendar.badge.exclamationmark",
        "calendar.day.timeline.left", "calendar.day.timeline.right",
        "book", "book.fill", "book.circle", "book.circle.fill",
        "book.closed", "book.closed.fill", "book.closed.circle", "book.closed.circle.fill",
        "books.vertical", "books.vertical.fill", "books.vertical.circle", "books.vertical.circle.fill",
        "book.and.wrench",
        "menucard", "menucard.fill",
        "magazine", "magazine.fill",
        "newspaper", "newspaper.fill", "newspaper.circle", "newspaper.circle.fill",
        "heart.text.square", "heart.text.square.fill",
        "scroll", "scroll.fill",
        "magnifyingglass", "magnifyingglass.circle", "magnifyingglass.circle.fill",
        "plus.magnifyingglass", "minus.magnifyingglass",
        "1.magnifyingglass", "arrow.up.left.and.down.right.magnifyingglass",
        "text.magnifyingglass",
        "loupe",
        "hammer", "hammer.fill", "hammer.circle", "hammer.circle.fill",
        "wrench", "wrench.fill", "wrench.adjustable", "wrench.adjustable.fill",
        "wrench.and.screwdriver", "wrench.and.screwdriver.fill",
        "screwdriver", "screwdriver.fill",
        "eyedropper", "eyedropper.halffull", "eyedropper.full",
        "paintbrush", "paintbrush.fill",
        "paintbrush.pointed", "paintbrush.pointed.fill",
        "level", "level.fill",
        "ruler", "ruler.fill",
        "scroll", "scroll.fill",
        "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
        "printer", "printer.fill", "printer.filled.and.paper",
        "scanner", "scanner.fill",
        "faxmachine", "faxmachine.fill",
        "briefcase", "briefcase.fill", "briefcase.circle", "briefcase.circle.fill",
        "case", "case.fill",
        "suitcase", "suitcase.fill",
        "suitcase.cart", "suitcase.cart.fill",
        "suitcase.rolling", "suitcase.rolling.fill",
        "theatermasks", "theatermasks.fill", "theatermasks.circle", "theatermasks.circle.fill",
        "puzzlepiece.extension", "puzzlepiece.extension.fill", "puzzlepiece", "puzzlepiece.fill",
        "sdcard", "sdcard.fill",
        "esim", "esim.fill",
        "film", "film.fill", "film.circle", "film.circle.fill",
        "film.stack", "film.stack.fill"
    ]

    // MARK: - Devices

    static let devices: [String] = [
        "desktopcomputer",
        "pc", "macpro.gen1", "macpro.gen2", "macpro.gen2.fill", "macpro.gen3", "macpro.gen3.fill",
        "macpro.gen3.server",
        "server.rack",
        "xserve",
        "laptopcomputer", "laptopcomputer.slash", "laptopcomputer.trianglebadge.exclamationmark",
        "macbook", "macbook.gen1", "macbook.gen2",
        "ipad", "ipad.badge.play", "ipad.landscape.badge.play",
        "ipad.gen1", "ipad.gen1.badge.play", "ipad.gen1.landscape.badge.play",
        "ipad.gen2", "ipad.gen2.badge.play", "ipad.gen2.landscape.badge.play",
        "ipad.rear.camera",
        "ipad.landscape", "ipad.gen1.landscape", "ipad.gen2.landscape",
        "iphone", "iphone.badge.play", "iphone.circle", "iphone.circle.fill",
        "iphone.gen1", "iphone.gen1.circle", "iphone.gen1.circle.fill",
        "iphone.gen1.badge.play",
        "iphone.gen2", "iphone.gen3", "iphone.gen3.badge.play",
        "iphone.rear.camera",
        "iphone.slash", "iphone.slash.circle", "iphone.slash.circle.fill",
        "smartphone",
        "apps.iphone", "apps.iphone.badge.plus", "apps.iphone.landscape",
        "ipod", "ipodtouch", "ipodtouch.landscape", "ipodtouch.slash",
        "ipodshuffle.gen1", "ipodshuffle.gen2", "ipodshuffle.gen3", "ipodshuffle.gen4",
        "flipphone", "candybarphone",
        "creditcard", "creditcard.fill", "creditcard.circle", "creditcard.circle.fill",
        "creditcard.and.123", "creditcard.trianglebadge.exclamationmark",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "network", "network.badge.shield.half.filled",
        "tv", "tv.fill", "tv.circle", "tv.circle.fill",
        "tv.inset.filled", "tv.slash", "tv.slash.fill",
        "4k.tv", "4k.tv.fill",
        "music.note.tv", "music.note.tv.fill",
        "play.tv", "play.tv.fill",
        "photo.tv",
        "display", "display.2", "display.trianglebadge.exclamationmark",
        "macmini", "macmini.fill",
        "macstudio", "macstudio.fill",
        "airport.extreme", "airport.extreme.tower", "airport.express",
        "homepod", "homepod.fill", "homepod.2", "homepod.2.fill",
        "homepodmini", "homepodmini.fill", "homepodmini.2", "homepodmini.2.fill",
        "hifispeaker", "hifispeaker.fill", "hifispeaker.2", "hifispeaker.2.fill",
        "appletv", "appletv.fill",
        "applewatch", "applewatch.watchface", "applewatch.radiowaves.left.and.right", "applewatch.slash",
        "applewatch.side.right", "applewatch.case.inset.filled",
        "watchface.applewatch.case",
        "airpodsmax", "beats.headphones", "headphones", "headphones.circle", "headphones.circle.fill",
        "earbuds", "earbuds.case.fill",
        "airpodspro", "airpodspro.chargingcase.wireless", "airpodspro.chargingcase.wireless.fill",
        "airpods", "airpods.chargingcase", "airpods.chargingcase.fill", "airpods.chargingcase.wireless",
        "airpods.gen3", "airpods.gen3.chargingcase.wireless",
        "beats.earphones", "beats.powerbeatspro", "beats.powerbeats", "beats.powerbeats3",
        "beats.studiobud.left", "beats.studiobud.right", "beats.studiobuds",
        "beats.studiobuds.chargingcase", "beats.studiobuds.chargingcase.fill",
        "beats.fit.pro", "beats.fit.pro.left", "beats.fit.pro.right",
        "beats.fit.pro.chargingcase", "beats.fit.pro.chargingcase.fill",
        "hifispeaker.and.homepod", "hifispeaker.and.homepod.fill",
        "hifispeaker.and.homepodmini", "hifispeaker.and.homepodmini.fill",
        "hifispeaker.and.appletv", "hifispeaker.and.appletv.fill",
        "homepod.and.appletv", "homepod.and.appletv.fill",
        "homepodmini.and.appletv", "homepodmini.and.appletv.fill",
        "applewatch.and.arrow.forward",
        "mediastick",
        "cable.connector", "cable.connector.horizontal",
        "radio", "radio.fill",
        "antenna.radiowaves.left.and.right", "antenna.radiowaves.left.and.right.slash",
        "antenna.radiowaves.left.and.right.circle", "antenna.radiowaves.left.and.right.circle.fill"
    ]

    // MARK: - Connectivity

    static let connectivity: [String] = [
        "wifi", "wifi.circle", "wifi.circle.fill",
        "wifi.square", "wifi.square.fill",
        "wifi.slash",
        "wifi.exclamationmark",
        "wifi.router", "wifi.router.fill",
        "network", "network.badge.shield.half.filled", "network.slash",
        "personalhotspot", "personalhotspot.circle", "personalhotspot.circle.fill",
        "bolt.horizontal", "bolt.horizontal.fill", "bolt.horizontal.circle", "bolt.horizontal.circle.fill",
        "ray.bottomleft", "ray.topleft", "ray.topright", "ray.bottomright",
        "dot.radiowaves.left.and.right", "dot.radiowaves.right",
        "dot.radiowaves.up.forward",
        "wave.3.left", "wave.3.left.circle", "wave.3.left.circle.fill",
        "wave.3.right", "wave.3.right.circle", "wave.3.right.circle.fill",
        "wave.3.backward", "wave.3.backward.circle", "wave.3.backward.circle.fill",
        "wave.3.forward", "wave.3.forward.circle", "wave.3.forward.circle.fill",
        "antenna.radiowaves.left.and.right", "antenna.radiowaves.left.and.right.slash",
        "antenna.radiowaves.left.and.right.circle", "antenna.radiowaves.left.and.right.circle.fill",
        "cellularbars", "chart.bar.fill", "chart.bar",
        "cellularbars.slash",
        "nfc", "nfc.fill",
        "gps",
        "touchid",
        "faceid",
        "shareplay", "shareplay.slash",
        "airdrop",
        "airplayvideo", "airplayvideo.circle", "airplayvideo.circle.fill",
        "airplayvideo.badge.exclamationmark",
        "airplayaudio", "airplayaudio.circle", "airplayaudio.circle.fill",
        "airplayaudio.badge.exclamationmark",
        "bluetoothlogo",
        "dot.arrowtriangles.up.right.down.left.circle"
    ]

    // MARK: - Transportation

    static let transportation: [String] = [
        "car", "car.fill", "car.circle", "car.circle.fill",
        "car.2", "car.2.fill",
        "car.side", "car.side.fill",
        "car.side.front.open", "car.side.front.open.fill",
        "car.side.rear.open", "car.side.rear.open.fill",
        "car.side.air.circulate", "car.side.air.circulate.fill",
        "car.side.air.fresh", "car.side.air.fresh.fill",
        "car.rear", "car.rear.fill",
        "bolt.car", "bolt.car.fill", "bolt.car.circle", "bolt.car.circle.fill",
        "car.ferry", "car.ferry.fill",
        "bus", "bus.fill", "bus.doubledecker", "bus.doubledecker.fill",
        "tram", "tram.fill", "tram.circle", "tram.circle.fill", "tram.fill.tunnel",
        "cablecar", "cablecar.fill",
        "lightrail", "lightrail.fill",
        "ferry", "ferry.fill",
        "sailboat", "sailboat.fill", "sailboat.circle", "sailboat.circle.fill",
        "airplane", "airplane.circle", "airplane.circle.fill",
        "airplane.departure", "airplane.arrival",
        "fuelpump", "fuelpump.fill", "fuelpump.circle", "fuelpump.circle.fill",
        "ev.charger", "ev.charger.fill", "ev.charger.slash", "ev.charger.slash.fill",
        "ev.charger.arrowtriangle.left", "ev.charger.arrowtriangle.left.fill",
        "ev.charger.arrowtriangle.right", "ev.charger.arrowtriangle.right.fill",
        "parkingsign", "parkingsign.circle", "parkingsign.circle.fill",
        "parkinglight", "parkinglight.fill",
        "fanblades", "fanblades.fill", "fanblades.slash", "fanblades.slash.fill",
        "bicycle", "bicycle.circle", "bicycle.circle.fill",
        "scooter",
        "road.lanes", "road.lanes.curved.left", "road.lanes.curved.right",
        "steeringwheel", "steeringwheel.slash",
        "car.window.right", "car.window.right.badge.exclamationmark",
        "carseat.left", "carseat.left.fill", "carseat.left.and.heat.waves", "carseat.left.and.heat.waves.fill",
        "carseat.right", "carseat.right.fill", "carseat.right.and.heat.waves", "carseat.right.and.heat.waves.fill",
        "carseat.left.fan", "carseat.left.fan.fill",
        "carseat.right.fan", "carseat.right.fan.fill",
        "carseat.left.massage", "carseat.left.massage.fill",
        "carseat.right.massage", "carseat.right.massage.fill",
        "key", "key.fill", "key.horizontal", "key.horizontal.fill"
    ]

    // MARK: - Human

    static let human: [String] = [
        "person", "person.fill",
        "person.circle", "person.circle.fill",
        "person.badge.plus", "person.fill.badge.plus",
        "person.badge.minus", "person.fill.badge.minus",
        "person.badge.clock", "person.badge.clock.fill",
        "person.badge.key", "person.badge.key.fill",
        "person.badge.shield.checkmark", "person.badge.shield.checkmark.fill",
        "person.and.arrow.left.and.arrow.right",
        "person.2", "person.2.fill",
        "person.2.circle", "person.2.circle.fill",
        "person.2.badge.gearshape", "person.2.badge.gearshape.fill",
        "person.2.badge.plus", "person.2.badge.plus.fill",
        "person.2.crop.square.stack", "person.2.crop.square.stack.fill",
        "person.3", "person.3.fill",
        "person.3.sequence", "person.3.sequence.fill",
        "person.crop.circle", "person.crop.circle.fill",
        "person.crop.circle.badge.plus", "person.crop.circle.fill.badge.plus",
        "person.crop.circle.badge.minus", "person.crop.circle.fill.badge.minus",
        "person.crop.circle.badge.checkmark", "person.crop.circle.fill.badge.checkmark",
        "person.crop.circle.badge.xmark", "person.crop.circle.fill.badge.xmark",
        "person.crop.circle.badge.questionmark", "person.crop.circle.badge.questionmark.fill",
        "person.crop.circle.badge.exclamationmark", "person.crop.circle.badge.exclamationmark.fill",
        "person.crop.circle.badge.moon", "person.crop.circle.badge.moon.fill",
        "person.crop.circle.badge.clock", "person.crop.circle.badge.clock.fill",
        "person.crop.square", "person.crop.square.fill",
        "person.crop.artframe",
        "person.crop.rectangle", "person.crop.rectangle.fill",
        "person.crop.rectangle.stack", "person.crop.rectangle.stack.fill",
        "photo.circle", "photo.circle.fill",
        "rectangle.inset.filled.and.person.filled",
        "person.text.rectangle", "person.text.rectangle.fill",
        "person.and.background.dotted",
        "person.wave.2", "person.wave.2.fill",
        "person.2.wave.2", "person.2.wave.2.fill",
        "figure.stand", "figure.stand.line.dotted.figure.stand",
        "figure.wave", "figure.wave.circle", "figure.wave.circle.fill",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.walk.motion", "figure.walk.motion.trianglebadge.exclamationmark",
        "figure.walk.arrival", "figure.walk.departure",
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.roll", "figure.roll.runningpace",
        "figure.american.football", "figure.archery", "figure.australian.football",
        "figure.badminton", "figure.barre", "figure.baseball", "figure.basketball",
        "figure.bowling", "figure.boxing", "figure.climbing", "figure.cooldown",
        "figure.core.training", "figure.cricket", "figure.cross.training",
        "figure.curling", "figure.dance", "figure.disc.sports", "figure.elliptical",
        "figure.equestrian.sports", "figure.fencing", "figure.fishing",
        "figure.flexibility", "figure.golf", "figure.gymnastics",
        "figure.hand.cycling", "figure.handball", "figure.highintensity.intervaltraining",
        "figure.hiking", "figure.hockey", "figure.hunting", "figure.indoor.cycle",
        "figure.jumprope", "figure.kickboxing", "figure.lacrosse",
        "figure.martial.arts", "figure.mind.and.body", "figure.mixed.cardio",
        "figure.open.water.swim", "figure.outdoor.cycle", "figure.pickleball",
        "figure.pilates", "figure.play", "figure.pool.swim", "figure.racquetball",
        "figure.rolling", "figure.rower", "figure.rugby", "figure.sailing",
        "figure.skating", "figure.skiing.crosscountry", "figure.skiing.downhill",
        "figure.snowboarding", "figure.soccer", "figure.socialdance",
        "figure.softball", "figure.squash", "figure.stair.stepper",
        "figure.stairs", "figure.step.training", "figure.strengthtraining.functional",
        "figure.strengthtraining.traditional", "figure.surfing", "figure.table.tennis",
        "figure.taichi", "figure.tennis", "figure.track.and.field",
        "figure.volleyball", "figure.water.fitness", "figure.waterpolo",
        "figure.wrestling", "figure.yoga",
        "figure.seated.seatbelt", "figure.seated.side"
    ]

    // MARK: - Nature

    static let nature: [String] = [
        "leaf", "leaf.fill", "leaf.circle", "leaf.circle.fill",
        "leaf.arrow.triangle.circlepath",
        "tree", "tree.fill", "tree.circle", "tree.circle.fill",
        "laurel.leading", "laurel.trailing",
        "globe", "globe.americas", "globe.americas.fill",
        "globe.europe.africa", "globe.europe.africa.fill",
        "globe.asia.australia", "globe.asia.australia.fill",
        "globe.central.south.asia", "globe.central.south.asia.fill",
        "globe.badge.chevron.backward",
        "globe.desk", "globe.desk.fill",
        "hare", "hare.fill", "tortoise", "tortoise.fill",
        "dog", "dog.fill", "dog.circle", "dog.circle.fill",
        "cat", "cat.fill", "cat.circle", "cat.circle.fill",
        "lizard", "lizard.fill", "lizard.circle", "lizard.circle.fill",
        "bird", "bird.fill", "bird.circle", "bird.circle.fill",
        "fish", "fish.fill", "fish.circle", "fish.circle.fill",
        "pawprint", "pawprint.fill", "pawprint.circle", "pawprint.circle.fill",
        "ant", "ant.fill", "ant.circle", "ant.circle.fill",
        "ladybug", "ladybug.fill", "ladybug.circle", "ladybug.circle.fill",
        "fossil.shell", "fossil.shell.fill",
        "carrot", "carrot.fill",
        "atom",
        "carbon.dioxide.cloud", "carbon.dioxide.cloud.fill",
        "carbon.monoxide.cloud", "carbon.monoxide.cloud.fill",
        "microbe", "microbe.fill", "microbe.circle", "microbe.circle.fill",
        "mount", "mountain.2", "mountain.2.fill", "mountain.2.circle", "mountain.2.circle.fill"
    ]

    // MARK: - Editing

    static let editing: [String] = [
        "pencil", "pencil.circle", "pencil.circle.fill", "pencil.slash",
        "square.and.pencil", "square.and.pencil.circle", "square.and.pencil.circle.fill",
        "rectangle.and.pencil.and.ellipsis",
        "scribble", "scribble.variable",
        "highlighter",
        "pencil.and.outline",
        "pencil.tip",
        "pencil.tip.crop.circle", "pencil.tip.crop.circle.badge.plus",
        "pencil.tip.crop.circle.badge.minus",
        "pencil.tip.crop.circle.badge.arrow.forward",
        "pencil.tip.crop.circle.fill",
        "lasso", "lasso.and.sparkles",
        "trash", "trash.fill", "trash.circle", "trash.circle.fill",
        "trash.slash", "trash.slash.fill",
        "trash.slash.circle", "trash.slash.circle.fill",
        "xmark", "xmark.circle", "xmark.circle.fill",
        "xmark.square", "xmark.square.fill",
        "xmark.rectangle", "xmark.rectangle.fill",
        "xmark.rectangle.portrait", "xmark.rectangle.portrait.fill",
        "xmark.octagon", "xmark.octagon.fill",
        "xmark.shield", "xmark.shield.fill",
        "checkmark", "checkmark.circle", "checkmark.circle.fill",
        "checkmark.square", "checkmark.square.fill",
        "checkmark.rectangle", "checkmark.rectangle.fill",
        "checkmark.rectangle.portrait", "checkmark.rectangle.portrait.fill",
        "checkmark.shield", "checkmark.shield.fill",
        "multiply", "multiply.circle", "multiply.circle.fill",
        "multiply.square", "multiply.square.fill",
        "minus", "minus.circle", "minus.circle.fill",
        "minus.square", "minus.square.fill",
        "minus.rectangle", "minus.rectangle.fill",
        "plus", "plus.circle", "plus.circle.fill",
        "plus.square", "plus.square.fill",
        "plus.rectangle", "plus.rectangle.fill",
        "plusminus", "plusminus.circle", "plusminus.circle.fill",
        "crop", "crop.rotate",
        "dial.low", "dial.low.fill", "dial.medium", "dial.medium.fill", "dial.high", "dial.high.fill",
        "gyroscope",
        "nosign",
        "aspectratio", "aspectratio.fill",
        "slider.horizontal.3",
        "slider.horizontal.below.rectangle", "slider.horizontal.below.square.filled.and.square",
        "slider.vertical.3",
        "rotate.left", "rotate.left.fill", "rotate.right", "rotate.right.fill",
        "rotate.3d", "rotate.3d.fill",
        "selection.pin.in.out",
        "externaldrive.badge.plus", "externaldrive.fill.badge.plus",
        "rectangle.dashed", "rectangle.dashed.badge.record"
    ]

    // MARK: - Text Formatting

    static let textFormatting: [String] = [
        "textformat", "textformat.alt",
        "textformat.size", "textformat.size.smaller", "textformat.size.larger",
        "textformat.abc", "textformat.abc.dottedunderline",
        "bold", "italic", "underline", "strikethrough",
        "bold.italic.underline", "bold.underline",
        "shadow",
        "a", "a.magnify",
        "abc",
        "textformat.subscript", "textformat.superscript",
        "textformat.12",
        "text.magnifyingglass",
        "character", "character.magnify", "character.textbox",
        "character.book.closed", "character.book.closed.fill",
        "textbox",
        "text.justify", "text.justify.left", "text.justify.right", "text.justify.leading", "text.justify.trailing",
        "text.alignleft", "text.aligncenter", "text.alignright",
        "text.redaction",
        "list.dash", "list.bullet", "list.bullet.circle", "list.bullet.circle.fill",
        "list.triangle", "list.star", "list.number",
        "list.bullet.indent",
        "list.bullet.below.rectangle",
        "text.line.first.and.arrowtriangle.forward",
        "text.line.last.and.arrowtriangle.forward",
        "increase.indent", "decrease.indent",
        "increase.quotelevel", "decrease.quotelevel",
        "text.insert",
        "text.append",
        "text.quote",
        "text.word.spacing",
        "paragraphsign",
        "text.cursor",
        "list.and.film",
        "line.3.horizontal", "line.3.horizontal.decrease", "line.3.horizontal.decrease.circle", "line.3.horizontal.decrease.circle.fill",
        "line.2.horizontal.decrease.circle", "line.2.horizontal.decrease.circle.fill"
    ]

    // MARK: - Media

    static let media: [String] = [
        "play", "play.fill", "play.circle", "play.circle.fill",
        "play.square", "play.square.fill",
        "play.rectangle", "play.rectangle.fill",
        "play.slash", "play.slash.fill",
        "pause", "pause.fill", "pause.circle", "pause.circle.fill",
        "pause.rectangle", "pause.rectangle.fill",
        "stop", "stop.fill", "stop.circle", "stop.circle.fill",
        "record.circle", "record.circle.fill",
        "playpause", "playpause.fill", "playpause.circle", "playpause.circle.fill",
        "backward", "backward.fill", "backward.circle", "backward.circle.fill",
        "forward", "forward.fill", "forward.circle", "forward.circle.fill",
        "backward.end", "backward.end.fill", "backward.end.circle", "backward.end.circle.fill",
        "forward.end", "forward.end.fill", "forward.end.circle", "forward.end.circle.fill",
        "backward.frame", "backward.frame.fill",
        "forward.frame", "forward.frame.fill",
        "shuffle", "shuffle.circle", "shuffle.circle.fill",
        "repeat", "repeat.circle", "repeat.circle.fill",
        "repeat.1", "repeat.1.circle", "repeat.1.circle.fill",
        "infinity", "infinity.circle", "infinity.circle.fill",
        "megaphone", "megaphone.fill",
        "speaker", "speaker.fill",
        "speaker.slash", "speaker.slash.fill", "speaker.slash.circle", "speaker.slash.circle.fill",
        "speaker.zzz", "speaker.zzz.fill",
        "speaker.wave.1", "speaker.wave.1.fill",
        "speaker.wave.2", "speaker.wave.2.fill", "speaker.wave.2.circle", "speaker.wave.2.circle.fill",
        "speaker.wave.3", "speaker.wave.3.fill",
        "speaker.badge.exclamationmark", "speaker.badge.exclamationmark.fill",
        "speaker.plus", "speaker.plus.fill",
        "speaker.minus", "speaker.minus.fill",
        "music.note", "music.note.list",
        "music.quarternote.3",
        "music.mic", "music.mic.circle", "music.mic.circle.fill",
        "goforward", "goforward.5", "goforward.10", "goforward.15", "goforward.30", "goforward.45", "goforward.60", "goforward.75", "goforward.90",
        "gobackward", "gobackward.5", "gobackward.10", "gobackward.15", "gobackward.30", "gobackward.45", "gobackward.60", "gobackward.75", "gobackward.90",
        "goforward.plus",
        "gobackward.minus",
        "swift",
        "scalemass", "scalemass.fill",
        "waveform", "waveform.circle", "waveform.circle.fill",
        "waveform.path.ecg", "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill",
        "waveform.path",
        "waveform.badge.plus", "waveform.badge.minus",
        "waveform.badge.exclamationmark",
        "photo", "photo.fill", "photo.circle", "photo.circle.fill",
        "photo.stack", "photo.stack.fill",
        "photo.on.rectangle", "photo.fill.on.rectangle.fill",
        "photo.on.rectangle.angled",
        "photo.artframe",
        "rectangle.on.rectangle.angled", "rectangle.fill.on.rectangle.angled.fill",
        "photo.tv",
        "rectangle.inset.filled",
        "rectangle.lefthalf.inset.filled", "rectangle.righthalf.inset.filled",
        "rectangle.tophalf.inset.filled", "rectangle.bottomhalf.inset.filled",
        "rectangle.lefthalf.inset.filled.arrow.left", "rectangle.righthalf.inset.filled.arrow.right",
        "rectangle.tophalf.filled", "rectangle.bottomhalf.filled",
        "livephoto", "livephoto.slash", "livephoto.badge.automatic",
        "video.slash", "video.slash.fill", "video.slash.circle", "video.slash.circle.fill",
        "arrow.up.right.video", "arrow.up.right.video.fill",
        "arrow.down.left.video", "arrow.down.left.video.fill",
        "rectangle.3.group", "rectangle.3.group.fill",
        "square.split.diagonal.2x2", "square.split.diagonal.2x2.fill",
        "rectangle.split.3x1", "rectangle.split.3x1.fill",
        "rectangle.split.3x3", "rectangle.split.3x3.fill"
    ]

    // MARK: - Keyboard

    static let keyboard: [String] = [
        "keyboard", "keyboard.badge.ellipsis", "keyboard.badge.ellipsis.fill",
        "keyboard.badge.eye", "keyboard.badge.eye.fill",
        "keyboard.chevron.compact.down", "keyboard.chevron.compact.down.fill",
        "keyboard.chevron.compact.left", "keyboard.chevron.compact.left.fill",
        "keyboard.onehanded.left", "keyboard.onehanded.left.fill",
        "keyboard.onehanded.right", "keyboard.onehanded.right.fill",
        "keyboard.fill",
        "globe.badge.chevron.backward",
        "command", "command.circle", "command.circle.fill",
        "command.square", "command.square.fill",
        "option", "alt",
        "control", "projective", "capslock", "capslock.fill",
        "shift", "shift.fill",
        "escape",
        "power", "power.circle", "power.circle.fill",
        "power.dotted",
        "sleep", "sleep.circle", "sleep.circle.fill",
        "wake", "wake.circle", "wake.circle.fill",
        "eject", "eject.fill", "eject.circle", "eject.circle.fill",
        "restart", "restart.circle", "restart.circle.fill",
        "clear", "clear.fill",
        "delete.left", "delete.left.fill",
        "delete.backward", "delete.backward.fill",
        "delete.right", "delete.right.fill",
        "delete.forward", "delete.forward.fill",
        "fn",
        "globe",
        "sun.max.circle", "sun.max.circle.fill",
        "light.max", "light.min",
        "return", "return.left", "return.right"
    ]

    // MARK: - Commerce

    static let commerce: [String] = [
        "cart", "cart.fill", "cart.circle", "cart.circle.fill",
        "cart.badge.plus", "cart.fill.badge.plus",
        "cart.badge.minus", "cart.fill.badge.minus",
        "cart.badge.questionmark", "cart.fill.badge.questionmark",
        "bag", "bag.fill", "bag.circle", "bag.circle.fill",
        "bag.badge.plus", "bag.fill.badge.plus",
        "bag.badge.minus", "bag.fill.badge.minus",
        "bag.badge.questionmark", "bag.fill.badge.questionmark",
        "creditcard", "creditcard.fill", "creditcard.circle", "creditcard.circle.fill",
        "creditcard.and.123", "creditcard.trianglebadge.exclamationmark",
        "giftcard", "giftcard.fill",
        "wallet.pass", "wallet.pass.fill",
        "wonsign", "wonsign.circle", "wonsign.circle.fill", "wonsign.square", "wonsign.square.fill",
        "dollarsign", "dollarsign.circle", "dollarsign.circle.fill", "dollarsign.square", "dollarsign.square.fill",
        "centsign", "centsign.circle", "centsign.circle.fill", "centsign.square", "centsign.square.fill",
        "yensign", "yensign.circle", "yensign.circle.fill", "yensign.square", "yensign.square.fill",
        "sterlingsign", "sterlingsign.circle", "sterlingsign.circle.fill", "sterlingsign.square", "sterlingsign.square.fill",
        "eurosign", "eurosign.circle", "eurosign.circle.fill", "eurosign.square", "eurosign.square.fill",
        "coloncurrencysign", "coloncurrencysign.circle", "coloncurrencysign.circle.fill", "coloncurrencysign.square", "coloncurrencysign.square.fill",
        "cruzeirosign", "cruzeirosign.circle", "cruzeirosign.circle.fill", "cruzeirosign.square", "cruzeirosign.square.fill",
        "brazilianrealsign", "brazilianrealsign.circle", "brazilianrealsign.circle.fill", "brazilianrealsign.square", "brazilianrealsign.square.fill",
        "pesetasign", "pesetasign.circle", "pesetasign.circle.fill", "pesetasign.square", "pesetasign.square.fill",
        "pesosign", "pesosign.circle", "pesosign.circle.fill", "pesosign.square", "pesosign.square.fill",
        "kaboruwazi", "kaboruwazi.circle", "kaboruwazi.circle.fill", "kaboruwazi.square", "kaboruwazi.square.fill",
        "guaranisign", "guaranisign.circle", "guaranisign.circle.fill", "guaranisign.square", "guaranisign.square.fill",
        "bahtsign", "bahtsign.circle", "bahtsign.circle.fill", "bahtsign.square", "bahtsign.square.fill",
        "rupeesign", "rupeesign.circle", "rupeesign.circle.fill", "rupeesign.square", "rupeesign.square.fill",
        "rublesign", "rublesign.circle", "rublesign.circle.fill", "rublesign.square", "rublesign.square.fill",
        "larisign", "larisign.circle", "larisign.circle.fill", "larisign.square", "larisign.square.fill",
        "manatsign", "manatsign.circle", "manatsign.circle.fill", "manatsign.square", "manatsign.square.fill",
        "tugriksign", "tugriksign.circle", "tugriksign.circle.fill", "tugriksign.square", "tugriksign.square.fill",
        "hryvniasign", "hryvniasign.circle", "hryvniasign.circle.fill", "hryvniasign.square", "hryvniasign.square.fill",
        "nairasign", "nairasign.circle", "nairasign.circle.fill", "nairasign.square", "nairasign.square.fill",
        "cedisign", "cedisign.circle", "cedisign.circle.fill", "cedisign.square", "cedisign.square.fill",
        "turkishlirasign", "turkishlirasign.circle", "turkishlirasign.circle.fill", "turkishlirasign.square", "turkishlirasign.square.fill",
        "sheqelsign", "sheqelsign.circle", "sheqelsign.circle.fill", "sheqelsign.square", "sheqelsign.square.fill",
        "bitcoinsign", "bitcoinsign.circle", "bitcoinsign.circle.fill", "bitcoinsign.square", "bitcoinsign.square.fill",
        "francsign", "francsign.circle", "francsign.circle.fill", "francsign.square", "francsign.square.fill",
        "florinsign", "florinsign.circle", "florinsign.circle.fill", "florinsign.square", "florinsign.square.fill",
        "kipsign", "kipsign.circle", "kipsign.circle.fill", "kipsign.square", "kipsign.square.fill",
        "tengesign", "tengesign.circle", "tengesign.circle.fill", "tengesign.square", "tengesign.square.fill",
        "indianrupeesign", "indianrupeesign.circle", "indianrupeesign.circle.fill", "indianrupeesign.square", "indianrupeesign.square.fill",
        "dongsign", "dongsign.circle", "dongsign.circle.fill", "dongsign.square", "dongsign.square.fill"
    ]

    // MARK: - Time

    static let time: [String] = [
        "clock", "clock.fill", "clock.circle", "clock.circle.fill",
        "clock.badge", "clock.badge.fill",
        "clock.badge.checkmark", "clock.badge.checkmark.fill",
        "clock.badge.exclamationmark", "clock.badge.exclamationmark.fill",
        "clock.badge.questionmark", "clock.badge.questionmark.fill",
        "clock.arrow.circlepath",
        "clock.arrow.2.circlepath",
        "deskclock", "deskclock.fill",
        "alarm", "alarm.fill",
        "alarm.waves.left.and.right", "alarm.waves.left.and.right.fill",
        "stopwatch", "stopwatch.fill",
        "timer", "timer.circle", "timer.circle.fill",
        "timer.square",
        "hourglass", "hourglass.circle", "hourglass.circle.fill",
        "hourglass.badge.plus",
        "hourglass.bottomhalf.filled",
        "hourglass.tophalf.filled"
    ]

    // MARK: - Health

    static let health: [String] = [
        "heart", "heart.fill", "heart.circle", "heart.circle.fill",
        "heart.slash", "heart.slash.fill", "heart.slash.circle", "heart.slash.circle.fill",
        "bolt.heart", "bolt.heart.fill",
        "heart.rectangle", "heart.rectangle.fill",
        "heart.text.square", "heart.text.square.fill",
        "cross", "cross.fill", "cross.circle", "cross.circle.fill",
        "cross.case", "cross.case.fill", "cross.case.circle", "cross.case.circle.fill",
        "pills", "pills.fill", "pills.circle", "pills.circle.fill",
        "capsule", "capsule.fill",
        "capsule.portrait", "capsule.portrait.fill",
        "bandage", "bandage.fill",
        "ivfluid.bag", "ivfluid.bag.fill",
        "syringe", "syringe.fill",
        "facemask", "facemask.fill",
        "medical.thermometer", "medical.thermometer.fill",
        "stethoscope", "stethoscope.circle", "stethoscope.circle.fill",
        "brain", "brain.head.profile", "brain.filled.head.profile",
        "ear", "ear.badge.checkmark", "ear.trianglebadge.exclamationmark", "ear.fill",
        "eye.slash", "eye.slash.fill", "eye.slash.circle", "eye.slash.circle.fill",
        "nose", "nose.fill",
        "mouth", "mouth.fill",
        "mustache", "mustache.fill",
        "lungs", "lungs.fill",
        "allergens", "allergens.fill",
        "hand.raised", "hand.raised.fill", "hand.raised.circle", "hand.raised.circle.fill",
        "hand.raised.slash", "hand.raised.slash.fill",
        "hand.point.up.left", "hand.point.up.left.fill",
        "hand.point.up", "hand.point.up.fill",
        "hand.point.up.braille", "hand.point.up.braille.fill",
        "hand.draw", "hand.draw.fill",
        "hand.tap", "hand.tap.fill",
        "hand.point.left", "hand.point.left.fill",
        "hand.point.right", "hand.point.right.fill",
        "hand.point.down", "hand.point.down.fill",
        "hand.wave", "hand.wave.fill",
        "hands.clap", "hands.clap.fill",
        "hands.sparkles", "hands.sparkles.fill",
        "waveform.path.ecg", "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill"
    ]

    // MARK: - Shapes

    static let shapes: [String] = [
        "circle", "circle.fill",
        "circle.lefthalf.filled", "circle.righthalf.filled",
        "circle.tophalf.filled", "circle.bottomhalf.filled",
        "circle.inset.filled",
        "circle.dashed", "circle.dashed.inset.filled",
        "circle.dotted",
        "circle.dotted.circle", "circle.dotted.circle.fill",
        "circlebadge", "circlebadge.fill", "circlebadge.2", "circlebadge.2.fill",
        "smallcircle.filled.circle", "smallcircle.filled.circle.fill",
        "smallcircle.circle", "smallcircle.circle.fill",
        "target",
        "capsule", "capsule.fill",
        "capsule.portrait", "capsule.portrait.fill",
        "capsule.lefthalf.filled", "capsule.righthalf.filled",
        "capsule.tophalf.filled", "capsule.bottomhalf.filled",
        "capsule.portrait.lefthalf.filled", "capsule.portrait.righthalf.filled",
        "capsule.portrait.tophalf.filled", "capsule.portrait.bottomhalf.filled",
        "capsule.inset.filled",
        "capsule.portrait.inset.filled",
        "oval", "oval.fill",
        "oval.lefthalf.filled", "oval.righthalf.filled",
        "oval.tophalf.filled", "oval.bottomhalf.filled",
        "oval.portrait", "oval.portrait.fill",
        "oval.portrait.lefthalf.filled", "oval.portrait.righthalf.filled",
        "oval.portrait.tophalf.filled", "oval.portrait.bottomhalf.filled",
        "oval.inset.filled", "oval.portrait.inset.filled",
        "square", "square.fill",
        "square.lefthalf.filled", "square.righthalf.filled",
        "square.tophalf.filled", "square.bottomhalf.filled",
        "square.inset.filled",
        "square.dashed", "square.dashed.inset.filled",
        "rectangle", "rectangle.fill",
        "rectangle.lefthalf.filled", "rectangle.righthalf.filled",
        "rectangle.tophalf.filled", "rectangle.bottomhalf.filled",
        "rectangle.inset.filled",
        "rectangle.portrait", "rectangle.portrait.fill",
        "rectangle.portrait.lefthalf.filled", "rectangle.portrait.righthalf.filled",
        "rectangle.portrait.tophalf.filled", "rectangle.portrait.bottomhalf.filled",
        "rectangle.portrait.inset.filled",
        "triangle", "triangle.fill",
        "triangle.lefthalf.filled", "triangle.righthalf.filled",
        "triangle.tophalf.filled", "triangle.bottomhalf.filled",
        "triangle.inset.filled",
        "diamond", "diamond.fill",
        "diamond.lefthalf.filled", "diamond.righthalf.filled",
        "diamond.tophalf.filled", "diamond.bottomhalf.filled",
        "diamond.inset.filled",
        "octagon", "octagon.fill",
        "octagon.lefthalf.filled", "octagon.righthalf.filled",
        "octagon.tophalf.filled", "octagon.bottomhalf.filled",
        "hexagon", "hexagon.fill",
        "hexagon.lefthalf.filled", "hexagon.righthalf.filled",
        "hexagon.tophalf.filled", "hexagon.bottomhalf.filled",
        "pentagon", "pentagon.fill",
        "pentagon.lefthalf.filled", "pentagon.righthalf.filled",
        "pentagon.tophalf.filled", "pentagon.bottomhalf.filled",
        "seal", "seal.fill",
        "shield", "shield.fill",
        "shield.lefthalf.filled", "shield.righthalf.filled",
        "shield.slash", "shield.slash.fill",
        "rhombus", "rhombus.fill",
        "star", "star.fill",
        "star.leadinghalf.filled",
        "app", "app.fill",
        "app.badge", "app.badge.fill",
        "app.dashed",
        "rectangle.on.rectangle", "rectangle.fill.on.rectangle.fill",
        "rectangle.on.rectangle.circle", "rectangle.on.rectangle.circle.fill",
        "rectangle.on.rectangle.square", "rectangle.on.rectangle.square.fill",
        "square.on.square", "square.fill.on.square.fill",
        "square.on.square.badge.person.crop", "square.on.square.badge.person.crop.fill",
        "square.on.square.dashed",
        "square.on.circle", "square.fill.on.circle.fill",
        "square.on.square.intersection.dashed",
        "rectangle.inset.topleft.filled", "rectangle.inset.topright.filled",
        "rectangle.inset.bottomleft.filled", "rectangle.inset.bottomright.filled",
        "rectangle.center.inset.filled",
        "rectangle.lefthalf.inset.filled.arrow.left", "rectangle.righthalf.inset.filled.arrow.right",
        "rectangle.tophalf.inset.filled.arrow.up",
        "rectangle.bottomhalf.inset.filled.arrow.down"
    ]

    // MARK: - Arrows

    static let arrows: [String] = [
        "arrow.up", "arrow.up.circle", "arrow.up.circle.fill",
        "arrow.up.square", "arrow.up.square.fill",
        "arrow.down", "arrow.down.circle", "arrow.down.circle.fill",
        "arrow.down.square", "arrow.down.square.fill",
        "arrow.left", "arrow.left.circle", "arrow.left.circle.fill",
        "arrow.left.square", "arrow.left.square.fill",
        "arrow.right", "arrow.right.circle", "arrow.right.circle.fill",
        "arrow.right.square", "arrow.right.square.fill",
        "arrow.up.left", "arrow.up.left.circle", "arrow.up.left.circle.fill",
        "arrow.up.left.square", "arrow.up.left.square.fill",
        "arrow.up.right", "arrow.up.right.circle", "arrow.up.right.circle.fill",
        "arrow.up.right.square", "arrow.up.right.square.fill",
        "arrow.down.left", "arrow.down.left.circle", "arrow.down.left.circle.fill",
        "arrow.down.left.square", "arrow.down.left.square.fill",
        "arrow.down.right", "arrow.down.right.circle", "arrow.down.right.circle.fill",
        "arrow.down.right.square", "arrow.down.right.square.fill",
        "arrow.up.arrow.down", "arrow.up.arrow.down.circle", "arrow.up.arrow.down.circle.fill",
        "arrow.up.arrow.down.square", "arrow.up.arrow.down.square.fill",
        "arrow.left.arrow.right", "arrow.left.arrow.right.circle", "arrow.left.arrow.right.circle.fill",
        "arrow.left.arrow.right.square", "arrow.left.arrow.right.square.fill",
        "arrow.turn.down.left", "arrow.turn.down.right",
        "arrow.turn.up.left", "arrow.turn.up.right",
        "arrow.turn.left.down", "arrow.turn.left.up",
        "arrow.turn.right.down", "arrow.turn.right.up",
        "arrow.uturn.left", "arrow.uturn.left.circle", "arrow.uturn.left.circle.fill",
        "arrow.uturn.left.circle.badge.ellipsis",
        "arrow.uturn.left.square", "arrow.uturn.left.square.fill",
        "arrow.uturn.right", "arrow.uturn.right.circle", "arrow.uturn.right.circle.fill",
        "arrow.uturn.right.square", "arrow.uturn.right.square.fill",
        "arrow.uturn.up", "arrow.uturn.up.circle", "arrow.uturn.up.circle.fill",
        "arrow.uturn.up.square", "arrow.uturn.up.square.fill",
        "arrow.uturn.down", "arrow.uturn.down.circle", "arrow.uturn.down.circle.fill",
        "arrow.uturn.down.square", "arrow.uturn.down.square.fill",
        "arrow.uturn.forward", "arrow.uturn.forward.circle", "arrow.uturn.forward.circle.fill",
        "arrow.uturn.forward.square", "arrow.uturn.forward.square.fill",
        "arrow.uturn.backward", "arrow.uturn.backward.circle", "arrow.uturn.backward.circle.fill",
        "arrow.uturn.backward.circle.badge.ellipsis",
        "arrow.uturn.backward.square", "arrow.uturn.backward.square.fill",
        "arrow.2.squarepath",
        "arrow.triangle.2.circlepath", "arrow.triangle.2.circlepath.circle", "arrow.triangle.2.circlepath.circle.fill",
        "exclamationmark.arrow.triangle.2.circlepath",
        "arrow.triangle.capsulepath",
        "arrow.3.trianglepath",
        "arrow.clockwise", "arrow.clockwise.circle", "arrow.clockwise.circle.fill",
        "arrow.counterclockwise", "arrow.counterclockwise.circle", "arrow.counterclockwise.circle.fill",
        "arrowshape.turn.up.left", "arrowshape.turn.up.left.fill",
        "arrowshape.turn.up.left.circle", "arrowshape.turn.up.left.circle.fill",
        "arrowshape.turn.up.right", "arrowshape.turn.up.right.fill",
        "arrowshape.turn.up.right.circle", "arrowshape.turn.up.right.circle.fill",
        "arrowshape.turn.up.left.2", "arrowshape.turn.up.left.2.fill",
        "arrowshape.turn.up.left.2.circle", "arrowshape.turn.up.left.2.circle.fill",
        "arrowshape.turn.up.backward", "arrowshape.turn.up.backward.fill",
        "arrowshape.turn.up.backward.circle", "arrowshape.turn.up.backward.circle.fill",
        "arrowshape.turn.up.forward", "arrowshape.turn.up.forward.fill",
        "arrowshape.turn.up.forward.circle", "arrowshape.turn.up.forward.circle.fill",
        "arrowshape.turn.up.backward.2", "arrowshape.turn.up.backward.2.fill",
        "arrowshape.turn.up.backward.2.circle", "arrowshape.turn.up.backward.2.circle.fill",
        "arrowshape.zigzag.right", "arrowshape.zigzag.right.fill",
        "arrowshape.zigzag.forward", "arrowshape.zigzag.forward.fill",
        "arrowshape.bounce.right", "arrowshape.bounce.right.fill",
        "arrowshape.bounce.forward", "arrowshape.bounce.forward.fill",
        "arrowshape.left", "arrowshape.left.fill",
        "arrowshape.right", "arrowshape.right.fill",
        "arrowshape.up", "arrowshape.up.fill",
        "arrowshape.down", "arrowshape.down.fill",
        "arrowtriangle.left", "arrowtriangle.left.fill",
        "arrowtriangle.left.circle", "arrowtriangle.left.circle.fill",
        "arrowtriangle.left.square", "arrowtriangle.left.square.fill",
        "arrowtriangle.right", "arrowtriangle.right.fill",
        "arrowtriangle.right.circle", "arrowtriangle.right.circle.fill",
        "arrowtriangle.right.square", "arrowtriangle.right.square.fill",
        "arrowtriangle.up", "arrowtriangle.up.fill",
        "arrowtriangle.up.circle", "arrowtriangle.up.circle.fill",
        "arrowtriangle.up.square", "arrowtriangle.up.square.fill",
        "arrowtriangle.down", "arrowtriangle.down.fill",
        "arrowtriangle.down.circle", "arrowtriangle.down.circle.fill",
        "arrowtriangle.down.square", "arrowtriangle.down.square.fill",
        "arrowtriangle.forward", "arrowtriangle.forward.fill",
        "arrowtriangle.forward.circle", "arrowtriangle.forward.circle.fill",
        "arrowtriangle.forward.square", "arrowtriangle.forward.square.fill",
        "arrowtriangle.backward", "arrowtriangle.backward.fill",
        "arrowtriangle.backward.circle", "arrowtriangle.backward.circle.fill",
        "arrowtriangle.backward.square", "arrowtriangle.backward.square.fill",
        "chevron.left", "chevron.left.circle", "chevron.left.circle.fill",
        "chevron.left.square", "chevron.left.square.fill",
        "chevron.right", "chevron.right.circle", "chevron.right.circle.fill",
        "chevron.right.square", "chevron.right.square.fill",
        "chevron.up", "chevron.up.circle", "chevron.up.circle.fill",
        "chevron.up.square", "chevron.up.square.fill",
        "chevron.down", "chevron.down.circle", "chevron.down.circle.fill",
        "chevron.down.square", "chevron.down.square.fill",
        "chevron.left.2", "chevron.right.2", "chevron.up.2", "chevron.down.2",
        "chevron.backward", "chevron.backward.circle", "chevron.backward.circle.fill",
        "chevron.backward.square", "chevron.backward.square.fill",
        "chevron.forward", "chevron.forward.circle", "chevron.forward.circle.fill",
        "chevron.forward.square", "chevron.forward.square.fill",
        "chevron.backward.2", "chevron.forward.2",
        "chevron.compact.left", "chevron.compact.right",
        "chevron.compact.up", "chevron.compact.down",
        "arrow.up.and.down.and.arrow.left.and.right",
        "arrow.up.left.and.down.right.and.arrow.up.right.and.down.left",
        "arrow.down.forward.and.arrow.up.backward",
        "arrow.down.forward.and.arrow.up.backward.circle",
        "arrow.down.forward.and.arrow.up.backward.circle.fill",
        "arrow.up.backward.and.arrow.down.forward",
        "arrow.up.backward.and.arrow.down.forward.circle",
        "arrow.up.backward.and.arrow.down.forward.circle.fill"
    ]

    // MARK: - Indices

    static let indices: [String] = [
        "a.circle", "a.circle.fill", "a.square", "a.square.fill",
        "b.circle", "b.circle.fill", "b.square", "b.square.fill",
        "c.circle", "c.circle.fill", "c.square", "c.square.fill",
        "d.circle", "d.circle.fill", "d.square", "d.square.fill",
        "e.circle", "e.circle.fill", "e.square", "e.square.fill",
        "f.circle", "f.circle.fill", "f.square", "f.square.fill",
        "g.circle", "g.circle.fill", "g.square", "g.square.fill",
        "h.circle", "h.circle.fill", "h.square", "h.square.fill",
        "i.circle", "i.circle.fill", "i.square", "i.square.fill",
        "j.circle", "j.circle.fill", "j.square", "j.square.fill",
        "k.circle", "k.circle.fill", "k.square", "k.square.fill",
        "l.circle", "l.circle.fill", "l.square", "l.square.fill",
        "m.circle", "m.circle.fill", "m.square", "m.square.fill",
        "n.circle", "n.circle.fill", "n.square", "n.square.fill",
        "o.circle", "o.circle.fill", "o.square", "o.square.fill",
        "p.circle", "p.circle.fill", "p.square", "p.square.fill",
        "q.circle", "q.circle.fill", "q.square", "q.square.fill",
        "r.circle", "r.circle.fill", "r.square", "r.square.fill",
        "s.circle", "s.circle.fill", "s.square", "s.square.fill",
        "t.circle", "t.circle.fill", "t.square", "t.square.fill",
        "u.circle", "u.circle.fill", "u.square", "u.square.fill",
        "v.circle", "v.circle.fill", "v.square", "v.square.fill",
        "w.circle", "w.circle.fill", "w.square", "w.square.fill",
        "x.circle", "x.circle.fill", "x.square", "x.square.fill",
        "y.circle", "y.circle.fill", "y.square", "y.square.fill",
        "z.circle", "z.circle.fill", "z.square", "z.square.fill",
        "0.circle", "0.circle.fill", "0.square", "0.square.fill",
        "1.circle", "1.circle.fill", "1.square", "1.square.fill",
        "2.circle", "2.circle.fill", "2.square", "2.square.fill",
        "3.circle", "3.circle.fill", "3.square", "3.square.fill",
        "4.circle", "4.circle.fill", "4.square", "4.square.fill",
        "5.circle", "5.circle.fill", "5.square", "5.square.fill",
        "6.circle", "6.circle.fill", "6.square", "6.square.fill",
        "7.circle", "7.circle.fill", "7.square", "7.square.fill",
        "8.circle", "8.circle.fill", "8.square", "8.square.fill",
        "9.circle", "9.circle.fill", "9.square", "9.square.fill",
        "00.circle", "00.circle.fill", "00.square", "00.square.fill",
        "01.circle", "01.circle.fill", "01.square", "01.square.fill",
        "02.circle", "02.circle.fill", "02.square", "02.square.fill",
        "03.circle", "03.circle.fill", "03.square", "03.square.fill",
        "04.circle", "04.circle.fill", "04.square", "04.square.fill",
        "05.circle", "05.circle.fill", "05.square", "05.square.fill",
        "06.circle", "06.circle.fill", "06.square", "06.square.fill",
        "07.circle", "07.circle.fill", "07.square", "07.square.fill",
        "08.circle", "08.circle.fill", "08.square", "08.square.fill",
        "09.circle", "09.circle.fill", "09.square", "09.square.fill",
        "10.circle", "10.circle.fill", "10.square", "10.square.fill",
        "11.circle", "11.circle.fill", "11.square", "11.square.fill",
        "12.circle", "12.circle.fill", "12.square", "12.square.fill",
        "13.circle", "13.circle.fill", "13.square", "13.square.fill",
        "14.circle", "14.circle.fill", "14.square", "14.square.fill",
        "15.circle", "15.circle.fill", "15.square", "15.square.fill",
        "16.circle", "16.circle.fill", "16.square", "16.square.fill",
        "17.circle", "17.circle.fill", "17.square", "17.square.fill",
        "18.circle", "18.circle.fill", "18.square", "18.square.fill",
        "19.circle", "19.circle.fill", "19.square", "19.square.fill",
        "20.circle", "20.circle.fill", "20.square", "20.square.fill",
        "21.circle", "21.circle.fill", "21.square", "21.square.fill",
        "22.circle", "22.circle.fill", "22.square", "22.square.fill",
        "23.circle", "23.circle.fill", "23.square", "23.square.fill",
        "24.circle", "24.circle.fill", "24.square", "24.square.fill",
        "25.circle", "25.circle.fill", "25.square", "25.square.fill",
        "26.circle", "26.circle.fill", "26.square", "26.square.fill",
        "27.circle", "27.circle.fill", "27.square", "27.square.fill",
        "28.circle", "28.circle.fill", "28.square", "28.square.fill",
        "29.circle", "29.circle.fill", "29.square", "29.square.fill",
        "30.circle", "30.circle.fill", "30.square", "30.square.fill",
        "31.circle", "31.circle.fill", "31.square", "31.square.fill",
        "32.circle", "32.circle.fill", "32.square", "32.square.fill",
        "33.circle", "33.circle.fill", "33.square", "33.square.fill",
        "34.circle", "34.circle.fill", "34.square", "34.square.fill",
        "35.circle", "35.circle.fill", "35.square", "35.square.fill",
        "36.circle", "36.circle.fill", "36.square", "36.square.fill",
        "37.circle", "37.circle.fill", "37.square", "37.square.fill",
        "38.circle", "38.circle.fill", "38.square", "38.square.fill",
        "39.circle", "39.circle.fill", "39.square", "39.square.fill",
        "40.circle", "40.circle.fill", "40.square", "40.square.fill",
        "41.circle", "41.circle.fill", "41.square", "41.square.fill",
        "42.circle", "42.circle.fill", "42.square", "42.square.fill",
        "43.circle", "43.circle.fill", "43.square", "43.square.fill",
        "44.circle", "44.circle.fill", "44.square", "44.square.fill",
        "45.circle", "45.circle.fill", "45.square", "45.square.fill",
        "46.circle", "46.circle.fill", "46.square", "46.square.fill",
        "47.circle", "47.circle.fill", "47.square", "47.square.fill",
        "48.circle", "48.circle.fill", "48.square", "48.square.fill",
        "49.circle", "49.circle.fill", "49.square", "49.square.fill",
        "50.circle", "50.circle.fill", "50.square", "50.square.fill"
    ]

    // MARK: - Math

    static let math: [String] = [
        "plus", "plus.circle", "plus.circle.fill", "plus.square", "plus.square.fill",
        "plus.rectangle", "plus.rectangle.fill",
        "plus.rectangle.portrait", "plus.rectangle.portrait.fill",
        "plus.diamond", "plus.diamond.fill",
        "minus", "minus.circle", "minus.circle.fill", "minus.square", "minus.square.fill",
        "minus.rectangle", "minus.rectangle.fill",
        "minus.rectangle.portrait", "minus.rectangle.portrait.fill",
        "minus.diamond", "minus.diamond.fill",
        "multiply", "multiply.circle", "multiply.circle.fill", "multiply.square", "multiply.square.fill",
        "divide", "divide.circle", "divide.circle.fill", "divide.square", "divide.square.fill",
        "equal", "equal.circle", "equal.circle.fill", "equal.square", "equal.square.fill",
        "lessthan", "lessthan.circle", "lessthan.circle.fill", "lessthan.square", "lessthan.square.fill",
        "greaterthan", "greaterthan.circle", "greaterthan.circle.fill", "greaterthan.square", "greaterthan.square.fill",
        "number", "number.circle", "number.circle.fill", "number.square", "number.square.fill",
        "x.squareroot",
        "plusminus", "plusminus.circle", "plusminus.circle.fill",
        "percent",
        "sum", "sum.fill",
        "function",
        "sigma",
        "plusminus", "plusminus.circle", "plusminus.circle.fill",
        "chevron.left.forwardslash.chevron.right",
        "angle",
        "fx", "fx.fill"
    ]

    // MARK: - Gaming

    static let gaming: [String] = [
        "gamecontroller", "gamecontroller.fill",
        "l.joystick", "l.joystick.fill",
        "r.joystick", "r.joystick.fill",
        "l.joystick.press.down", "l.joystick.press.down.fill",
        "r.joystick.press.down", "r.joystick.press.down.fill",
        "l.joystick.tilt.left", "l.joystick.tilt.left.fill",
        "l.joystick.tilt.right", "l.joystick.tilt.right.fill",
        "l.joystick.tilt.up", "l.joystick.tilt.up.fill",
        "l.joystick.tilt.down", "l.joystick.tilt.down.fill",
        "r.joystick.tilt.left", "r.joystick.tilt.left.fill",
        "r.joystick.tilt.right", "r.joystick.tilt.right.fill",
        "r.joystick.tilt.up", "r.joystick.tilt.up.fill",
        "r.joystick.tilt.down", "r.joystick.tilt.down.fill",
        "dpad", "dpad.fill",
        "dpad.left.filled", "dpad.right.filled",
        "dpad.up.filled", "dpad.down.filled",
        "circle.grid.cross", "circle.grid.cross.fill",
        "circle.grid.cross.left.filled", "circle.grid.cross.up.filled",
        "circle.grid.cross.right.filled", "circle.grid.cross.down.filled",
        "l.button.roundedbottom.horizontal", "l.button.roundedbottom.horizontal.fill",
        "r.button.roundedbottom.horizontal", "r.button.roundedbottom.horizontal.fill",
        "l1.button.roundedbottom.horizontal", "l1.button.roundedbottom.horizontal.fill",
        "r1.button.roundedbottom.horizontal", "r1.button.roundedbottom.horizontal.fill",
        "l2.button.roundedtop.horizontal", "l2.button.roundedtop.horizontal.fill",
        "r2.button.roundedtop.horizontal", "r2.button.roundedtop.horizontal.fill",
        "lb.button.roundedbottom.horizontal", "lb.button.roundedbottom.horizontal.fill",
        "rb.button.roundedbottom.horizontal", "rb.button.roundedbottom.horizontal.fill",
        "lt.button.roundedtop.horizontal", "lt.button.roundedtop.horizontal.fill",
        "rt.button.roundedtop.horizontal", "rt.button.roundedtop.horizontal.fill",
        "zl.button.roundedtop.horizontal", "zl.button.roundedtop.horizontal.fill",
        "zr.button.roundedtop.horizontal", "zr.button.roundedtop.horizontal.fill",
        "logo.playstation", "logo.xbox",
        "playstation.logo",
        "xbox.logo",
        "house.lodge", "house.lodge.fill",
        "tent", "tent.fill", "tent.2", "tent.2.fill",
        "mountain.2", "mountain.2.fill",
        "flag.checkered", "flag.checkered.2.crossed",
        "flag.filled.and.flag.crossed", "flag.and.flag.filled.crossed",
        "trophy", "trophy.fill", "trophy.circle", "trophy.circle.fill",
        "medal", "medal.fill",
        "crown", "crown.fill",
        "die.face.1", "die.face.1.fill",
        "die.face.2", "die.face.2.fill",
        "die.face.3", "die.face.3.fill",
        "die.face.4", "die.face.4.fill",
        "die.face.5", "die.face.5.fill",
        "die.face.6", "die.face.6.fill",
        "pianokeys", "pianokeys.inverse",
        "paintpalette", "paintpalette.fill",
        "puzzlepiece", "puzzlepiece.fill",
        "puzzlepiece.extension", "puzzlepiece.extension.fill"
    ]

    // MARK: - Privacy

    static let privacy: [String] = [
        "lock", "lock.fill", "lock.circle", "lock.circle.fill",
        "lock.square", "lock.square.fill",
        "lock.square.stack", "lock.square.stack.fill",
        "lock.rectangle", "lock.rectangle.fill",
        "lock.rectangle.stack", "lock.rectangle.stack.fill",
        "lock.rectangle.on.rectangle", "lock.rectangle.on.rectangle.fill",
        "lock.shield", "lock.shield.fill",
        "lock.slash", "lock.slash.fill",
        "lock.open", "lock.open.fill",
        "lock.open.rotation", "lock.open.rotation.fill",
        "lock.rotation", "lock.rotation.fill",
        "lock.open.trianglebadge.exclamationmark",
        "lock.open.trianglebadge.exclamationmark.fill",
        "key", "key.fill",
        "key.horizontal", "key.horizontal.fill",
        "key.icloud", "key.icloud.fill",
        "key.slash", "key.slash.fill",
        "key.viewfinder",
        "person.badge.key", "person.badge.key.fill",
        "hand.raised", "hand.raised.fill",
        "hand.raised.circle", "hand.raised.circle.fill",
        "hand.raised.square", "hand.raised.square.fill",
        "hand.raised.slash", "hand.raised.slash.fill",
        "shield", "shield.fill",
        "shield.slash", "shield.slash.fill",
        "shield.lefthalf.filled", "shield.righthalf.filled",
        "shield.checkered",
        "checkmark.shield", "checkmark.shield.fill",
        "xmark.shield", "xmark.shield.fill",
        "exclamationmark.shield", "exclamationmark.shield.fill",
        "questionmark.key.filled",
        "eye.slash", "eye.slash.fill", "eye.slash.circle", "eye.slash.circle.fill",
        "person.badge.shield.checkmark", "person.badge.shield.checkmark.fill",
        "touchid", "faceid", "opticid"
    ]

    // MARK: - Home

    static let home: [String] = [
        "house", "house.fill", "house.circle", "house.circle.fill",
        "house.lodge", "house.lodge.fill",
        "house.and.flag", "house.and.flag.fill",
        "house.and.flag.circle", "house.and.flag.circle.fill",
        "music.note.house", "music.note.house.fill",
        "playpause.circle.fill",
        "building", "building.fill",
        "building.2", "building.2.fill", "building.2.crop.circle", "building.2.crop.circle.fill",
        "building.columns", "building.columns.fill",
        "building.columns.circle", "building.columns.circle.fill",
        "lightbulb", "lightbulb.fill",
        "lightbulb.circle", "lightbulb.circle.fill",
        "lightbulb.slash", "lightbulb.slash.fill",
        "lightbulb.min", "lightbulb.min.fill",
        "lightbulb.max", "lightbulb.max.fill",
        "lightbulb.2", "lightbulb.2.fill",
        "lightbulb.led", "lightbulb.led.fill",
        "lightbulb.led.wide", "lightbulb.led.wide.fill",
        "lamp.desk", "lamp.desk.fill",
        "lamp.table", "lamp.table.fill",
        "lamp.floor", "lamp.floor.fill",
        "lamp.ceiling", "lamp.ceiling.fill",
        "lamp.ceiling.inverse",
        "light.recessed", "light.recessed.fill", "light.recessed.inverse", "light.recessed.3.inverse",
        "chandelier", "chandelier.fill",
        "light.panel", "light.panel.fill",
        "light.strip.2", "light.strip.2.fill",
        "fan", "fan.fill",
        "fan.desk", "fan.desk.fill",
        "fan.floor", "fan.floor.fill",
        "fan.ceiling", "fan.ceiling.fill",
        "fan.oscillation", "fan.oscillation.fill",
        "fan.and.light.ceiling", "fan.and.light.ceiling.fill",
        "fanblades", "fanblades.fill", "fanblades.slash", "fanblades.slash.fill",
        "bed.double", "bed.double.fill", "bed.double.circle", "bed.double.circle.fill",
        "sofa", "sofa.fill",
        "chair", "chair.fill",
        "chair.lounge", "chair.lounge.fill",
        "bathtub", "bathtub.fill",
        "shower", "shower.fill", "shower.handheld", "shower.handheld.fill", "shower.sidejet", "shower.sidejet.fill",
        "toilet", "toilet.fill",
        "sink", "sink.fill",
        "spigot", "spigot.fill",
        "washer", "washer.fill",
        "dryer", "dryer.fill",
        "dishwasher", "dishwasher.fill",
        "oven", "oven.fill",
        "stove", "stove.fill",
        "cooktop", "cooktop.fill",
        "microwave", "microwave.fill",
        "refrigerator", "refrigerator.fill",
        "air.conditioner.horizontal", "air.conditioner.horizontal.fill",
        "air.conditioner.vertical", "air.conditioner.vertical.fill",
        "air.purifier", "air.purifier.fill",
        "dehumidifier", "dehumidifier.fill",
        "humidifier", "humidifier.fill",
        "heater.vertical", "heater.vertical.fill",
        "fireplace", "fireplace.fill",
        "sprinkler", "sprinkler.fill", "sprinkler.and.droplets", "sprinkler.and.droplets.fill",
        "drop.keypad.rectangle", "drop.keypad.rectangle.fill",
        "faucet", "faucet.fill",
        "blinds.vertical.open", "blinds.vertical.closed",
        "blinds.horizontal.open", "blinds.horizontal.closed",
        "curtains.open", "curtains.closed",
        "roller.shade.open", "roller.shade.closed",
        "window.vertical.open", "window.vertical.closed",
        "window.horizontal", "window.horizontal.closed",
        "window.awning.open", "window.awning.closed",
        "window.ceiling", "window.ceiling.closed",
        "window.casement", "window.casement.closed",
        "door.left.hand.open", "door.left.hand.closed",
        "door.right.hand.open", "door.right.hand.closed",
        "door.french.open", "door.french.closed",
        "door.garage.open", "door.garage.closed",
        "door.garage.double.bay.open", "door.garage.double.bay.closed",
        "door.sliding.left.hand.open", "door.sliding.left.hand.closed",
        "door.sliding.right.hand.open", "door.sliding.right.hand.closed",
        "sensor", "sensor.fill",
        "sensor.tag.radiowaves.forward", "sensor.tag.radiowaves.forward.fill",
        "smoke", "smoke.fill", "smoke.circle", "smoke.circle.fill",
        "carbon.monoxide.cloud", "carbon.monoxide.cloud.fill",
        "carbon.dioxide.cloud", "carbon.dioxide.cloud.fill",
        "video.doorbell", "video.doorbell.fill"
    ]

    // MARK: - Fitness

    static let fitness: [String] = [
        "figure.run", "figure.run.circle", "figure.run.circle.fill",
        "figure.walk", "figure.walk.circle", "figure.walk.circle.fill",
        "figure.walk.motion", "figure.walk.motion.trianglebadge.exclamationmark",
        "figure.stand", "figure.stand.line.dotted.figure.stand",
        "figure.wave", "figure.wave.circle", "figure.wave.circle.fill",
        "figure.fall", "figure.fall.circle", "figure.fall.circle.fill",
        "figure.roll",
        "figure.roll.runningpace",
        "figure.american.football",
        "figure.archery",
        "figure.australian.football",
        "figure.badminton",
        "figure.barre",
        "figure.baseball",
        "figure.basketball",
        "figure.bowling",
        "figure.boxing",
        "figure.climbing",
        "figure.cooldown",
        "figure.core.training",
        "figure.cricket",
        "figure.cross.training",
        "figure.curling",
        "figure.dance",
        "figure.disc.sports",
        "figure.elliptical",
        "figure.equestrian.sports",
        "figure.fencing",
        "figure.fishing",
        "figure.flexibility",
        "figure.golf",
        "figure.gymnastics",
        "figure.hand.cycling",
        "figure.handball",
        "figure.highintensity.intervaltraining",
        "figure.hiking",
        "figure.hockey",
        "figure.hunting",
        "figure.indoor.cycle",
        "figure.jumprope",
        "figure.kickboxing",
        "figure.lacrosse",
        "figure.martial.arts",
        "figure.mind.and.body",
        "figure.mixed.cardio",
        "figure.open.water.swim",
        "figure.outdoor.cycle",
        "figure.pickleball",
        "figure.pilates",
        "figure.play",
        "figure.pool.swim",
        "figure.racquetball",
        "figure.rolling",
        "figure.rower",
        "figure.rugby",
        "figure.sailing",
        "figure.skating",
        "figure.skiing.crosscountry",
        "figure.skiing.downhill",
        "figure.snowboarding",
        "figure.soccer",
        "figure.socialdance",
        "figure.softball",
        "figure.squash",
        "figure.stair.stepper",
        "figure.stairs",
        "figure.step.training",
        "figure.strengthtraining.functional",
        "figure.strengthtraining.traditional",
        "figure.surfing",
        "figure.table.tennis",
        "figure.taichi",
        "figure.tennis",
        "figure.track.and.field",
        "figure.volleyball",
        "figure.water.fitness",
        "figure.waterpolo",
        "figure.wrestling",
        "figure.yoga",
        "sportscourt", "sportscourt.fill",
        "sportscourt.circle", "sportscourt.circle.fill",
        "soccerball", "soccerball.inverse",
        "baseball", "baseball.fill", "baseball.circle", "baseball.circle.fill",
        "basketball", "basketball.fill", "basketball.circle", "basketball.circle.fill",
        "football", "football.fill", "football.circle", "football.circle.fill",
        "tennis.racket", "tennis.racket.circle", "tennis.racket.circle.fill",
        "tennisball", "tennisball.fill", "tennisball.circle", "tennisball.circle.fill",
        "volleyball", "volleyball.fill", "volleyball.circle", "volleyball.circle.fill",
        "hockey.puck", "hockey.puck.fill", "hockey.puck.circle", "hockey.puck.circle.fill",
        "cricket.ball", "cricket.ball.fill", "cricket.ball.circle", "cricket.ball.circle.fill",
        "dumbbell", "dumbbell.fill",
        "scalemass", "scalemass.fill",
        "heart", "heart.fill", "heart.circle", "heart.circle.fill",
        "waveform.path.ecg", "waveform.path.ecg.rectangle", "waveform.path.ecg.rectangle.fill"
    ]
}
